### ISSUE TITLE
creating a release for FreeBSD port

### ISSUE THREAD

**Issue by xanderio** [rixx/django-context-decorator#5]
I currently creating a Port for the FreeBSD operating system. I would be helpful if this repository had a release.

If can help in any way, just poke me.

**Comment by rixx** [comment]
Oh, you can't reference PyPI releases for FreeBSD ports? Or git tags?

I can create a GitHub release if that's really required, but I'd like to keep the release workflow fairly simple, so may I ask what GitHub releases offer over PyPI releases or git tags?

**Comment by xanderio** [comment]
Since posting this issue i found the documentation for pulling from PyPI.
For reference: https://wiki.freebsd.org/Python/PortsPolicy#MASTER_SITES


Closing this issue.

**Comment by xanderio** [comment]
https://wiki.freebsd.org/Python/PortsPolicy#MASTER_SITES
